name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "0de7ad47f547afcaca7575c5c24ad560"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "fx.axz.me", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "a63a48dfdf31415eac7f0e16c3f2c8f8" },
  { binding = "PBIMGS", id ="7747fa4dc22f46d99e27e51741642de0" }
]

[site]
bucket = "./static/dist"
